services:
  invokeai-presets-service:
    build: .
    container_name: invokeai-models-container
    environment:
      - LC_ALL=C.UTF-8
      - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:$PATH
      - PATH=$PATH:/home/invokeaiuser/.local/bin
    volumes:
      - .:/home/invokeaiuser
      - ${INVOKE_AI_DIR}:/home/invokeaiuser/InvokeAI
    working_dir: /home/invokeaiuser
    command: ["bash"]